Errors should not should "Error: " twice for an error message.
Using the command line:
office-addin-manifest modify test\manifests\manifest.xml

The output was appearing as:
Error: Error: You need to specify something to change in the manifest.

Fixed so the output appears as:
Error: You need to specify something to change in the manifest.